// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Collections;

namespace IntelliCRMAPIService.Postgres
{
    public partial class Users
    {
        public Users()
        {
            Userdetails = new HashSet<Userdetails>();
        }

        public int Userid { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string Rolename { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Contactnumber { get; set; }
        public int? Accountstatus { get; set; }
        public int? Accounttype { get; set; }
        public BitArray Rightsforcustomeraccount { get; set; }
        public string Createdby { get; set; }
        public DateOnly? Createddate { get; set; }
        public string Modifiedby { get; set; }
        public DateOnly? Modifieddate { get; set; }

        public virtual ICollection<Userdetails> Userdetails { get; set; }
    }
}