// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IntelliCRMAPIService.DBContext.DBEntities
{
    public partial class Apiusers
    {
        [Key]
        public int ApiuserId { get; set; }
        public string ApiuserName { get; set; }
        public string Apipassword { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }
    }
}