// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IntelliCRMAPIService
{
    public partial class UserDetails
    {
        [Key]
        public int UserDetailsID { get; set; }
        public int? UserId_Fk { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Coutry { get; set; }
        public double? CreditLimit { get; set; }
        public double? SoareceviedAmount { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }

        [NotMapped]
        public virtual Users UserIdFkNavigation { get; set; }
    }
}