// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IntelliCRMAPIService
{
    public partial class Productmaster
    {
        public int Productid { get; set; }
        public string Category { get; set; }
        public string Equsbrandname { get; set; }
        public string Activeingredient { get; set; }
        public string Nameonpackage { get; set; }
        public string Strength { get; set; }
        public string Dosageform { get; set; }
        public int? Unitsperpack { get; set; }
        public string Productsourcedfrom { get; set; }
        public string Manufacturer { get; set; }
        public string Licenceholder { get; set; }
        public string Batch { get; set; }
        public DateTime? Expirydaterange { get; set; }
        public double? Cifpriceperpack { get; set; }
        public double? Sellingpriceperpack { get; set; }
        public double? Weight { get; set; }
        public string Boe { get; set; }
        public string Rxwarningcautionarynote { get; set; }
        public int? Qty { get; set; }
        public string Createdby { get; set; }
        public DateTime? Createddate { get; set; }
        public string Modifiedby { get; set; }
        public DateTime? Modifieddate { get; set; }
        [NotMapped]
        public string RequestedBy { get; set; }
    }
}