// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IntelliCRMAPIService.Attribute;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IntelliCRMAPIService
{
    public partial class Users
    {
        public Users()
        {
            Customerproduct = new HashSet<Customerproduct>();
            Userdetails = new HashSet<Userdetails>();
        }

        public int Userid { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string Rolename { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Contactnumber { get; set; }
        public int? Accountstatus { get; set; }
        public int? Accounttype { get; set; }
        public bool? Rightsforcustomeraccount { get; set; }
        public string Createdby { get; set; }
        public DateTime? Createddate { get; set; }
        public string Modifiedby { get; set; }
        public DateTime? Modifieddate { get; set; }

        [NotMapped]
        public Role Role { get; set; }

        public virtual ICollection<Customerproduct> Customerproduct { get; set; }
        public virtual ICollection<Userdetails> Userdetails { get; set; }
    }
}